- name: configure the basho proserv repository
  template: src=etc_apt_sources.list.d_bashoproserv.list.j2 dest=/etc/apt/sources.list.d/bashoproserv.list

- name: install debs
  apt: pkg={{item }} state=present
  with_items:
  - bashobench
  - python-pip
